# Generated by Django 4.1.7 on 2023-06-09 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('idd', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleRegistration',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('codee', models.CharField(max_length=50)),
                ('regis_date', models.CharField(max_length=50)),
                ('expiration_date', models.CharField(max_length=50)),
                ('regis_center', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('license_plate', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('plate', models.CharField(max_length=50)),
                ('regis_date', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('model_code', models.CharField(max_length=50)),
                ('man_year', models.CharField(max_length=50)),
                ('man_country', models.CharField(max_length=50)),
                ('engine_no', models.CharField(max_length=50)),
                ('chassis_no', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
                ('sit', models.CharField(max_length=10)),
                ('load', models.CharField(blank=True, max_length=10, null=True)),
                ('modification', models.CharField(blank=True, max_length=50, null=True)),
                ('lifetime_limit', models.CharField(blank=True, max_length=20, null=True)),
                ('regis_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vehicleregistration')),
            ],
        ),
    ]
