# Generated by Django 4.2 on 2023-06-13 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_vehicleregistration_platee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleregistration',
            old_name='platee',
            new_name='my_platee',
        ),
    ]
