# Generated by Django 4.2 on 2023-06-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_platee_vehicleregistration_my_platee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleregistration',
            name='my_platee',
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='my_plate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
